FROM python:3.10-alpine

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
# Install dependencies
COPY ./django-app/requirements.txt /requirements.txt
RUN pip install -r ./requirements.txt

COPY ./django-app /django-app
WORKDIR /django-app/django_app
