FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
# Install dependencies
COPY ./django-app/requirements.txt /requirements.txt
RUN pip install -r ./requirements.txt
RUN apt update
RUN apt install -y protobuf-compiler
WORKDIR /app
COPY ./django-app .
