FROM golang:1.22-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY ./go .


# Download all dependencies
RUN go mod tidy

# Expose port 8080 to the outside world
EXPOSE 8080
