version: '3.8'

services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/app
    command: sh -c "go build -o main ./server/server.go && ./main"
    environment:
      - GO_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=testdb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
