version: '3.8'

services:
  go-server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/app
    command: sh -c "go build -o ./cmd/main ./cmd/main.go && sleep 15s && ./cmd/main"
    environment:
      - GO_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=testdb
    depends_on:
      - mysql
  
  django-server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-django
    ports:
      - "8081:8081"
    volumes:
      - ./django-app/django_app:/django_app
    command: >
      sh -c "ls && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8081"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
